version: '3.8'

services:

  db:
    image: "postgres:13.4-alpine"
    container_name: "postgres-container"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  planner-service:
    build: .
    container_name: planner
    ports:
      - 8993:8994
    environment:
      - DB_SERVER=jdbc:postgresql://db:5432/postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    links:
      - db
