version: '1'

services:

  postgresql:
    image: "postgres:13.4-alpine"
    container_name: "postgres-container"
    ports:
      - 5432:5432

  planner-service:
    build: ./planner
    container_name: planner
    ports:
      - 8993:8994
    links:
      - postgresql
