server:
  port: 8993

spring:

  jpa:
    hibernate:
      # https://stackoverflow.com/questions/438146/what-are-the-possible-values-of-the-hibernate-hbm2ddl-auto-configuration-and-wha
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

